#!/bin/bash
# Soshnikov Vasiliy <dedok.mad@gmail.com>

# globs envt variables 
REPO_ROOT=$(pwd)
TOOLCHAINS_DIR=$REPO_ROOT/toolchains

TOOLCHAIN_MACOSX_UNIVERSAL_FILE=MacOS.Universal.cmake
TOOLCHAIN_LUNIX_UNIVERSAL_FILE=
TOOLCHAIN_WINDOWS_UNIVERSAL_FILE=

